# Generated by Django 3.1.2 on 2020-12-06 21:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201018_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/default_city.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
