# Generated by Django 3.1.2 on 2020-12-06 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201206_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
