# Generated by Django 3.1.2 on 2020-12-06 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dnleezjj1/image/upload/v1607289651/vakswo7ai7e9njbn7tfw.jpg', max_length=255, verbose_name='Header Image'),
        ),
    ]
