# Generated by Django 3.1.2 on 2020-12-06 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201206_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='upload/v1607289651/vakswo7ai7e9njbn7tfw.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
