# Generated by Django 3.1.2 on 2020-12-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201206_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='header_image',
        ),
    ]
