# Generated by Django 3.1.2 on 2020-12-06 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201206_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='mountains-863474_960_720_ngyyc8.jpg', max_length=255, verbose_name='Header Image'),
        ),
    ]
