# Generated by Django 3.1.2 on 2020-12-06 22:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_profile_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='mountains-863474_960_720_ngyyc8.jpg', max_length=255, null=True, verbose_name='Header Image'),
        ),
    ]
